name: ZMT Crawler

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.6
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: run toutiao crawler
        run: |
          python toutiao_crawler.py --times ${{ vars.CRAWLER_TIMES }} --sleeps ${{ vars.CRAWLER_SLEEPS }} --mongo_url ${{ secrets.MONGO_URL}} --cookie "${{ secrets.CRAWLER_COOKIE}}" 