name: toutiao user crawler

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.6
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: run toutiao crawler zfy
        run: |
          python ./src/toutiao_user_crawler.py --mongo_url ${{ secrets.MONGO_URL}} --mongo_username ${{ secrets.MONGO_USERNAME}} --mongo_password ${{ secrets.MONGO_PASSWORD}}  
